if(EXISTS "${SRC}")
  execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${SRC}" "${DST}")
  if(MAKE_EXECUTABLE)
    execute_process(COMMAND ${CMAKE_COMMAND} -E chmod +x "${DST}")
  endif()
  message(STATUS "Bundled engine: ${SRC} -> ${DST}")
else()
  message(WARNING "Engine binary not found (skipping bundle): ${SRC}")
endif()
